# Settings relevant for the hitobito_oeku wagon
# Overrides settings from the main application
application:
  logo:
    image: logo-gray.svg
    width: 200
    height: 68
    background_color: none
  languages:
    de: Deutsch
    fr: Français
    it: Italiano

  # non UI languages for assigning to person#language
  # additional_languages:
  #   en: Englisch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito-oeku@puzzle.ch

phone_number:
  custom_label:
    enabled: false

social_account:
  custom_label:
    enabled: false

additional_email:
  custom_label:
    enabled: false

additional_address:
  custom_label:
    enabled: false
